export const FETCH_CURRENCY_STARTED = 'FETCH_CURRENCY_STARTED'
export const FETCH_CURRENCY_SUCCESS = 'FETCH_CURRENCY_SUCCESS'
export const FETCH_CURRENCY_FAILURE = 'FETCH_CURRENCY_FAILURE'

export const CHANGE_CURRENCY = 'CHANGE_CURRENCY'
